import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Our Products - Website Packages & Pricing',
  description: 'Explore AtarWebb\'s affordable website packages. From starter sites to professional enterprise solutions. Competitive pricing for Africa and America. Custom web development tailored to your business needs.',
  keywords: [
    // Ecommerce & Online Store Keywords
    'ecommerce website for small shops south africa', 'cheap online store for south african businesses', 'online store kenya cheap', 'ecommerce website under kes 20,000', 'ecommerce website under r2000 south africa', 'ecommerce website nairobi cheap', 'ecommerce website for local shops kenya', 'online store developers kenya', 'online store developers sa', 'ecommerce website rwanda cheap', 'online store rwanda', 'affordable ecommerce websites south africa', 'affordable ecommerce rwanda', 'wordpress ecommerce south africa', 'wordpress ecommerce kenya', 'wordpress ecommerce rwanda', 'shopify setup south africa cheap', 'shopify kenya setup', 'shopify setup rwanda', 'shopify website developers south africa', 'shopify developers kenya', 'shopify developers rwanda',
    // Industry-Specific Website Keywords - South Africa
    'website for beauty salons south africa', 'website design for barbershops south africa', 'website for restaurants in durban', 'website developers for real estate agents johannesburg', 'website for clothing boutiques south africa', 'website for construction companies south africa', 'website design for plumbers in durban', 'electrician website developers south africa', 'website for transport companies south africa', 'taxi booking website south africa', 'logistics website design south africa', 'trucking company website south africa', 'law firm website south africa', 'accounting firm website south africa', 'HR agency website south africa', 'recruitment website south africa', 'school website design south africa', 'church website developers south africa', 'ngo website design south africa', 'website for doctors and clinics south africa', 'dentist website south africa', 'hotel website developers south africa', 'guesthouse booking website south africa', 'website for wedding planners south africa', 'website for events company south africa', 'website for tutoring services south africa', 'website for personal trainers south africa', 'website for influencers south africa', 'portfolio website design south africa', 'website for property listings south africa', 'website for security companies south africa', 'website for cleaning services south africa', 'accounting website design south africa', 'website for freelancers south africa', 'online booking system south africa', 'donation website design south africa', 'charity website south africa', 'taxi app website south africa', 'marketplace website south africa', 'membership website design south africa', 'website for consultants south africa', 'website for digital creators south africa', 'ecommerce for small business south africa', 'website redesign services south africa', 'whatsapp integrated website south africa', 'website for home services south africa', 'landing page design south africa',
    // Industry-Specific Website Keywords - Kenya
    'website for boutiques kenya', 'website design for real estate agents kenya', 'plumber website kenya', 'electrician website kenya', 'website for salons kenya', 'website for barbershops kenya', 'website for hotels in kenya', 'website for guesthouses kenya', 'website for doctors kenya', 'dentist website kenya', 'website for churches kenya', 'school website developers kenya', 'cheap website for NGOs kenya', 'website for consultancies kenya', 'website for accountants kenya', 'trucking company website kenya', 'taxi booking website kenya', 'logistics website kenya', 'website for immigration consultants kenya', 'website for influencers kenya', 'fitness coach website kenya', 'personal brand website kenya', 'real estate listing website kenya', 'hair vendor website kenya', 'online booking website kenya', 'digital agency website kenya', 'website for cleaning services kenya', 'charity website kenya', 'donation platform kenya', 'membership website kenya', 'custom landing page kenya', 'business profile website kenya', 'portfolio website nairobi', 'home services website kenya', 'website redesign kenya', 'website for travel agents kenya', 'online marketplace kenya', 'website for rental services kenya', 'NGO wordpress website kenya', 'corporate website kenya', 'affordable business website kenya',
    // Industry-Specific Website Keywords - Rwanda
    'website for schools rwanda', 'church website rwanda', 'ngo website rwanda', 'website for doctors rwanda', 'hospital website design rwanda', 'real estate website rwanda', 'property listing website kigali', 'website for salons rwanda', 'website for beauty shops rwanda', 'website for restaurants rwanda', 'hotel booking website rwanda', 'guesthouse website rwanda', 'tourism website rwanda', 'plumber website rwanda', 'electrician website rwanda', 'contractor website rwanda', 'construction website rwanda', 'trucking company website rwanda', 'transport company website rwanda', 'logistics website rwanda', 'startup website rwanda', 'online booking website rwanda', 'website for freelancers rwanda', 'portfolio website design rwanda', 'consulting website rwanda', 'accountant website kigali', 'website for events rwanda', 'event booking website rwanda', 'membership website rwanda', 'landing page design rwanda', 'cleaning company website rwanda', 'repair services website rwanda', 'immigration consultants website rwanda', 'professional website kigali', 'cheap business website rwanda', 'restaurant menu website rwanda', 'website for personal brands rwanda', 'salon booking website kigali', 'marketplace website rwanda', 'website redesign rwanda', 'website for legal services rwanda', 'travel agency website rwanda', 'real estate developer website rwanda', 'website for tutors rwanda', 'website for influencers rwanda', 'boutique website kigali', 'charity website rwanda', 'donation website rwanda', 'low cost website kigali',
    // Pricing & Package Keywords
    'website packages', 'website pricing', 'affordable websites', 'web development pricing', 'custom website', 'business website packages', 'website under R1000', 'website under KES 10,000', 'website under RWF 50,000', 'website under r2000 south africa', 'website under r1000 south africa', 'website under kes 10,000', 'website under rwf 50,000', 'website design pay monthly south africa', 'kenya web design packages cheap', 'website design packages kenya', 'rwanda website design packages', 'affordable website design for small business south africa', 'affordable website design kenya for small business', 'affordable website design rwanda', 'cheap website design kenya', 'cheap website design rwanda', 'affordable web design south africa', 'cheap web design south africa', 'affordable website design kenya', 'affordable website design rwanda'
  ],
  openGraph: {
    title: 'AtarWebb Products - Website Packages & Pricing',
    description: 'Explore our affordable website packages. From starter sites to professional enterprise solutions.',
    url: 'https://atarwebb.com/products',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AtarWebb Products - Website Packages & Pricing',
    description: 'Explore our affordable website packages. From starter sites to professional enterprise solutions.',
  },
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children
}

