// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/Beezee-App/app/[country]/[industry]/beehive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/beehive">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/beehive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/cash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/cash">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/cash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/credit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/credit">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/credit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/help">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/more/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/more">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/more/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/reports">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/services">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/stock">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/tour/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/tour">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/tour/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/app/[country]/[industry]/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/app/[country]/[industry]/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/route/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Beezee-App/route">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/route/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-login">> = Specific
  const handler = {} as typeof import("../../src/app/admin-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/beehive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/beehive">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/beehive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/conversion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/conversion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/conversion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/beehive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/beehive">> = Specific
  const handler = {} as typeof import("../../src/app/admin/beehive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data">> = Specific
  const handler = {} as typeof import("../../src/app/admin/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/admin/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tables/[tableName]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tables/[tableName]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tables/[tableName]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tables">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/atarwebb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/atarwebb">> = Specific
  const handler = {} as typeof import("../../src/app/atarwebb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/beezee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beezee">> = Specific
  const handler = {} as typeof import("../../src/app/beezee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/beezee/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beezee/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/beezee/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/beezee/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beezee/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/beezee/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/beezee/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beezee/terms">> = Specific
  const handler = {} as typeof import("../../src/app/beezee/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/comparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comparison">> = Specific
  const handler = {} as typeof import("../../src/app/comparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline-test">> = Specific
  const handler = {} as typeof import("../../src/app/offline-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/simple-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simple-test">> = Specific
  const handler = {} as typeof import("../../src/app/simple-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tanstack-comparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tanstack-comparison">> = Specific
  const handler = {} as typeof import("../../src/app/tanstack-comparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tanstack-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tanstack-test">> = Specific
  const handler = {} as typeof import("../../src/app/tanstack-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/metrics/beehive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics/beehive">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/metrics/beehive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/metrics/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/metrics/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/check-phone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-phone">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/check-phone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/lookup-business/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/lookup-business">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/lookup-business/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-pin">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/beehive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beehive">> = Specific
  const handler = {} as typeof import("../../src/app/api/beehive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/manifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manifest">> = Specific
  const handler = {} as typeof import("../../src/app/api/manifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/Beezee-App/app/[country]/[industry]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/Beezee-App/app/[country]/[industry]">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/app/[country]/[industry]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/Beezee-App/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/Beezee-App">> = Specific
  const handler = {} as typeof import("../../src/app/Beezee-App/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/auth">> = Specific
  const handler = {} as typeof import("../../src/app/admin/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/atarwebb/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/atarwebb">> = Specific
  const handler = {} as typeof import("../../src/app/atarwebb/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
