#!/usr/bin/env ts-node

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config({ path: '.env.local' });

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const KYSHI_SECRET_KEY = process.env.KYSHI_SECRET_KEY!;
const KYSHI_BASE_URL = process.env.KYSHI_BASE_URL || 'https://api.kyshi.co/v1';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// After creating plans in Kyshi dashboard, update these codes:
const MANUAL_PLAN_CODES = {
  GH: 'GH_WEEKLY_20',        // Replace with actual code from Kyshi dashboard
  NG: 'NG_WEEKLY_500',       // Replace with actual code from Kyshi dashboard
  ZA: 'ZA_WEEKLY_50',        // Replace with actual code from Kyshi dashboard
  CI: 'PLN_IVD0jEfuxAwh-Z-'  // Replace with actual code from Kyshi dashboard
};

async function verifyPlanInKyshi(code: string): Promise<boolean> {
  try {
    const response = await fetch(`${KYSHI_BASE_URL}/plans/${code}`, {
      method: 'GET',
      headers: {
        'x-api-key': KYSHI_SECRET_KEY,
        'Content-Type': 'application/json',
      },
    });
    return response.ok;
  } catch {
    return false;
  }
}

async function updatePlanCodes() {
  console.log('🔄 Updating Kyshi plan codes in Supabase...\n');

  const plans = [
    { country_code: 'GH', name: 'Beezee Weekly Ghana', amount: 20, currency: 'GHS', code: MANUAL_PLAN_CODES.GH },
    { country_code: 'NG', name: 'Beezee Weekly Nigeria', amount: 500, currency: 'NGN', code: MANUAL_PLAN_CODES.NG },
    { country_code: 'ZA', name: 'Beezee Weekly South Africa', amount: 30, currency: 'ZAR', code: MANUAL_PLAN_CODES.ZA },
    { country_code: 'CI', name: 'Beezee Weekly Côte d\'Ivoire', amount: 1000, currency: 'XOF', code: MANUAL_PLAN_CODES.CI }
  ];

  for (const plan of plans) {
    console.log(`\n📍 ${plan.country_code}: ${plan.name}`);
    console.log(`   Code: ${plan.code}`);

    // Verify plan exists in Kyshi
    const exists = await verifyPlanInKyshi(plan.code);
    if (!exists) {
      console.log('   ⚠️  WARNING: Plan code not found in Kyshi!');
      console.log('   Please create this plan in Kyshi dashboard first.');
      continue;
    }
    console.log('   ✅ Verified in Kyshi');

    // Update Supabase
    const { error } = await supabase
      .from('kyshi_plans')
      .upsert({
        country_code: plan.country_code,
        name: plan.name,
        amount: plan.amount,
        currency: plan.currency,
        interval: 'weekly',
        kyshi_plan_code: plan.code,
        is_active: true
      }, {
        onConflict: 'country_code'
      });

    if (error) {
      console.log('   ❌ Database update failed:', error.message);
    } else {
      console.log('   ✅ Updated in Supabase');
    }
  }

  // Show final database state
  console.log('\n\n📊 Current Plans in Database:\n');
  const { data, error } = await supabase
    .from('kyshi_plans')
    .select('country_code, name, amount, currency, kyshi_plan_code, is_active')
    .eq('is_active', true)
    .order('country_code');

  if (error) {
    console.log('Error fetching plans:', error);
  } else {
    console.table(data);
  }

  console.log('\n✨ Update complete!');
}

// Instructions
console.log('╔════════════════════════════════════════════════════════════════╗');
console.log('║  Kyshi Plan Code Updater                                       ║');
console.log('╚════════════════════════════════════════════════════════════════╝\n');
console.log('📋 INSTRUCTIONS:');
console.log('1. Create plans manually in Kyshi Dashboard (https://kyshi.co/dashboard)');
console.log('2. Copy the plan codes generated by Kyshi');
console.log('3. Update MANUAL_PLAN_CODES in this script (line 13-18)');
console.log('4. Run this script again to update Supabase\n');
console.log('⚠️  NOTE: Kyshi API only supports KES. Other currencies must be');
console.log('   created manually through the dashboard.\n');

updatePlanCodes();
