var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/auth/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fea4e46a._.js")
R.c("server/chunks/ssr/d605f_next_dist_420fe1bb._.js")
R.c("server/chunks/ssr/Downloads_WebApp_WebApp-main_modern-website_7f4f4d07._.js")
R.c("server/chunks/ssr/[root-of-the-server]__175a3434._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5b48d60d._.js")
R.c("server/chunks/ssr/d605f_next_dist_f496acfd._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_global-error_d20299a3.js")
R.c("server/chunks/ssr/[root-of-the-server]__7beb96cc._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_45af40e7._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_forbidden_cf9f2ee3.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_unauthorized_31601ba0.js")
R.c("server/chunks/ssr/Downloads_WebApp_WebApp-main_modern-website_src_app_admin_layout_tsx_12b35cf9._.js")
R.c("server/chunks/ssr/6c7f9_WebApp_WebApp-main_modern-website_src_app_admin_auth_layout_tsx_4b1b80dd._.js")
R.c("server/chunks/ssr/b3575_modern-website__next-internal_server_app_admin_auth_login_page_actions_f05c519a.js")
R.m(36912)
module.exports=R.m(36912).exports
