var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/simple-test/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a4f33daf._.js")
R.c("server/chunks/ssr/d605f_next_dist_420fe1bb._.js")
R.c("server/chunks/ssr/Downloads_WebApp_WebApp-main_modern-website_e6c7c8ec._.js")
R.c("server/chunks/ssr/[root-of-the-server]__175a3434._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5b48d60d._.js")
R.c("server/chunks/ssr/d605f_next_dist_f496acfd._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_global-error_d20299a3.js")
R.c("server/chunks/ssr/[root-of-the-server]__7beb96cc._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_45af40e7._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_forbidden_cf9f2ee3.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_unauthorized_31601ba0.js")
R.c("server/chunks/ssr/b3575_modern-website__next-internal_server_app_simple-test_page_actions_bf21a92b.js")
R.m(45415)
module.exports=R.m(45415).exports
