// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/Beezee-App/app/[country]/[industry]" | "/Beezee-App/app/[country]/[industry]/beehive" | "/Beezee-App/app/[country]/[industry]/calendar" | "/Beezee-App/app/[country]/[industry]/cash" | "/Beezee-App/app/[country]/[industry]/credit" | "/Beezee-App/app/[country]/[industry]/help" | "/Beezee-App/app/[country]/[industry]/more" | "/Beezee-App/app/[country]/[industry]/notifications" | "/Beezee-App/app/[country]/[industry]/reports" | "/Beezee-App/app/[country]/[industry]/services" | "/Beezee-App/app/[country]/[industry]/settings" | "/Beezee-App/app/[country]/[industry]/stock" | "/Beezee-App/app/[country]/[industry]/tour" | "/Beezee-App/app/[country]/[industry]/transactions" | "/Beezee-App/auth/login" | "/Beezee-App/auth/signup" | "/Beezee-App/route" | "/admin" | "/admin-login" | "/admin/analytics" | "/admin/analytics/beehive" | "/admin/analytics/conversion" | "/admin/analytics/revenue" | "/admin/analytics/users" | "/admin/auth/login" | "/admin/beehive" | "/admin/dashboard" | "/admin/data" | "/admin/marketing" | "/admin/revenue" | "/admin/tables" | "/admin/tables/[tableName]" | "/admin/users" | "/atarwebb" | "/beezee" | "/beezee/privacy" | "/beezee/refunds" | "/beezee/terms" | "/comparison" | "/demo" | "/offline-test" | "/privacy" | "/simple-test" | "/tanstack-comparison" | "/tanstack-test" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/metrics/beehive" | "/api/admin/metrics/overview" | "/api/auth/check-phone" | "/api/auth/lookup-business" | "/api/auth/signup" | "/api/auth/verify-pin" | "/api/beehive" | "/api/expenses" | "/api/manifest" | "/api/transactions"
type PageRoutes = never
type LayoutRoutes = "/" | "/Beezee-App" | "/Beezee-App/app/[country]/[industry]" | "/admin" | "/admin/auth" | "/atarwebb"
type RedirectRoutes = never
type RewriteRoutes = "/Beezee-App/sw.js" | "/kenya/app/[[...path]]" | "/nigeria/app/[[...path]]" | "/south-africa/app/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin-login": {}
  "/admin/analytics": {}
  "/admin/analytics/beehive": {}
  "/admin/analytics/conversion": {}
  "/admin/analytics/revenue": {}
  "/admin/analytics/users": {}
  "/admin/auth": {}
  "/admin/auth/login": {}
  "/admin/beehive": {}
  "/admin/dashboard": {}
  "/admin/data": {}
  "/admin/marketing": {}
  "/admin/revenue": {}
  "/admin/tables": {}
  "/admin/tables/[tableName]": { "tableName": string; }
  "/admin/users": {}
  "/api/admin/metrics/beehive": {}
  "/api/admin/metrics/overview": {}
  "/api/auth/check-phone": {}
  "/api/auth/lookup-business": {}
  "/api/auth/signup": {}
  "/api/auth/verify-pin": {}
  "/api/beehive": {}
  "/api/expenses": {}
  "/api/manifest": {}
  "/api/transactions": {}
  "/atarwebb": {}
  "/beezee": {}
  "/Beezee-App": {}
  "/Beezee-App/app/[country]/[industry]": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/beehive": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/calendar": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/cash": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/credit": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/help": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/more": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/notifications": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/reports": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/services": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/settings": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/stock": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/tour": { "country": string; "industry": string; }
  "/Beezee-App/app/[country]/[industry]/transactions": { "country": string; "industry": string; }
  "/Beezee-App/auth/login": {}
  "/Beezee-App/auth/signup": {}
  "/Beezee-App/route": {}
  "/Beezee-App/sw.js": {}
  "/beezee/privacy": {}
  "/beezee/refunds": {}
  "/beezee/terms": {}
  "/comparison": {}
  "/demo": {}
  "/kenya/app/[[...path]]": { "path"?: string[]; }
  "/nigeria/app/[[...path]]": { "path"?: string[]; }
  "/offline-test": {}
  "/privacy": {}
  "/simple-test": {}
  "/south-africa/app/[[...path]]": { "path"?: string[]; }
  "/tanstack-comparison": {}
  "/tanstack-test": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/auth": never
  "/atarwebb": never
  "/Beezee-App": never
  "/Beezee-App/app/[country]/[industry]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
