import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import JSZip from 'jszip'

function getSupabaseClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!supabaseUrl || !supabaseServiceKey) {
    throw new Error('Supabase configuration missing')
  }
  return createClient(supabaseUrl, supabaseServiceKey)
}

export async function GET(
  request: NextRequest,
  { params }: { params: { draftId: string } }
) {
  try {
    const supabase = getSupabaseClient()
    const { draftId } = params

    // Get user from session cookie or auth header
    // For now, we'll check via draft ownership

    // Get draft project
    const { data: draft, error } = await supabase
      .from('draft_projects')
      .select('*')
      .eq('id', draftId)
      .single()

    if (error || !draft) {
      return NextResponse.json({ error: 'Draft not found' }, { status: 404 })
    }

    // Check if user has buyout
    const { data: account } = await supabase
      .from('user_accounts')
      .select('*')
      .eq('id', draft.user_id)
      .single()

    if (!account?.has_buyout) {
      return NextResponse.json({ 
        error: 'Buyout required. Please purchase a buyout to download the code.' 
      }, { status: 403 })
    }

    // Get HTML code
    const htmlCode = draft.metadata?.html_code
    if (!htmlCode) {
      return NextResponse.json({ error: 'Code not available' }, { status: 404 })
    }

    // Create ZIP file
    const zip = new JSZip()
    
    // Add main HTML file
    zip.file('index.html', htmlCode)
    
    // Add README
    const readme = `# ${draft.business_name} Website

Generated by AtarWebb AI Website Builder

## Setup Instructions

1. Extract all files to a folder
2. Open index.html in a web browser
3. For production, upload to any web hosting service

## Customization

You can edit index.html directly to customize your website.
All styles and scripts are included in the single HTML file.

## Support

For questions or support, visit https://atarwebb.com

---
Generated: ${new Date().toISOString()}
Business: ${draft.business_name}
Location: ${draft.business_location}
`
    zip.file('README.md', readme)

    // Generate ZIP
    const zipBuffer = await zip.generateAsync({ type: 'uint8array' })

    // Return ZIP file
    return new NextResponse(new Uint8Array(zipBuffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${slugify(draft.business_name)}-website.zip"`,
      },
    })
  } catch (error: any) {
    console.error('Download error:', error)
    return NextResponse.json({ error: 'Failed to generate download' }, { status: 500 })
  }
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 50)
}

