-- Migration: Add Idempotency Keys Table
-- Purpose: Track processed idempotency keys to prevent duplicate operations
-- Created: 2024

-- Create idempotency_keys table
CREATE TABLE IF NOT EXISTS idempotency_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  feature TEXT NOT NULL,
  operation_type TEXT NOT NULL,
  user_id TEXT NOT NULL,
  response_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '24 hours')
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_key ON idempotency_keys(key);
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_expires_at ON idempotency_keys(expires_at);
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_user_id ON idempotency_keys(user_id);

-- Create function to automatically clean up expired keys
CREATE OR REPLACE FUNCTION cleanup_expired_idempotency_keys()
RETURNS void AS $$
BEGIN
  DELETE FROM idempotency_keys
  WHERE expires_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- Create a scheduled job to run cleanup (requires pg_cron extension)
-- If pg_cron is not available, this should be run manually or via a cron job
-- SELECT cron.schedule('cleanup-idempotency-keys', '0 * * * *', 'SELECT cleanup_expired_idempotency_keys()');

-- Add comment to table
COMMENT ON TABLE idempotency_keys IS 'Stores idempotency keys to prevent duplicate operations during offline sync';
COMMENT ON COLUMN idempotency_keys.key IS 'Unique idempotency key generated by client';
COMMENT ON COLUMN idempotency_keys.feature IS 'Feature name (cash, inventory, calendar, credit, beehive)';
COMMENT ON COLUMN idempotency_keys.operation_type IS 'Type of operation (sale, expense, add_item, etc.)';
COMMENT ON COLUMN idempotency_keys.user_id IS 'User or business ID that created the operation';
COMMENT ON COLUMN idempotency_keys.response_data IS 'Original response data to return for duplicate requests';
COMMENT ON COLUMN idempotency_keys.expires_at IS 'Expiration timestamp (24 hours from creation)';
