var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/analytics/revenue/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f2f314b2._.js")
R.c("server/chunks/ssr/d605f_next_dist_420fe1bb._.js")
R.c("server/chunks/ssr/Downloads_WebApp_WebApp-main_modern-website_e2606f4c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__175a3434._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5b48d60d._.js")
R.c("server/chunks/ssr/d605f_next_dist_f496acfd._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_global-error_d20299a3.js")
R.c("server/chunks/ssr/[root-of-the-server]__7beb96cc._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_45af40e7._.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_forbidden_cf9f2ee3.js")
R.c("server/chunks/ssr/d605f_next_dist_client_components_builtin_unauthorized_31601ba0.js")
R.c("server/chunks/ssr/Downloads_WebApp_WebApp-main_modern-website_src_app_admin_layout_tsx_12b35cf9._.js")
R.c("server/chunks/ssr/a8d1d__next-internal_server_app_admin_analytics_revenue_page_actions_3718e82d.js")
R.m(96916)
module.exports=R.m(96916).exports
